### PR TITLE
Make grpc-services.jar optional + remove grpc health service setup

### LINKED ISSUE #411: java.lang.ClassNotFoundException: io.grpc.services.HealthStatusManager
**The context**

Create a gRPC server using `grpc-spring-boot-starter` library.

**The bug**

Even when `grpc.server.healthServiceEnabled=false`, `GrpcServerAutoConfiguration` tries to create a `HealthStatusManager`, which fails with a `ClassNotFoundException` if `io.grpc:grpc-services` is not on the classpath. Now, if the application has indicated that it doesn't want to enable health service, there's no reason for it to add an unnecessary jar on the classpath that is "secretly" needed by the `grpc-spring-boot-starter` library.

My suggestion is to check for the presence of the class, as well as the property `grpc.server.healthServiceEnabled`, before creating the `HealthStatusManager`.

**Stacktrace and logs**

```
java.lang.IllegalStateException: Error processing condition on net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration.defaultGrpcServerProperties
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:60)
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108)
	...
Caused by: java.lang.IllegalStateException: Failed to introspect Class [net.devh.boot.grpc.server.autoconfigure.GrpcServerAutoConfiguration] from ClassLoader [jdk.internal.loader.ClassLoaders$AppClassLoader@9e89d68]
	at org.springframework.util.ReflectionUtils.getDeclaredMethods(ReflectionUtils.java:481)
	...
Caused by: java.lang.NoClassDefFoundError: io/grpc/services/HealthStatusManager
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	...
Caused by: java.lang.ClassNotFoundException: io.grpc.services.HealthStatusManager
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	...
```

**Steps to Reproduce**

N/A

**The application's environment**

Which versions do you use?
* Spring (boot): 2.3.1.RELEASE
* grpc-java: 1.30.2
* grpc-spring-boot-starter: 2.9.0.RELEASE

**Additional context**

* Did it ever work before? No
* Do you have a demo? No

### PR DESCRIPTION
**Pull request by ST-DDT**
Fixes #411 , #501

Remove the grpc-service setup from the server factory making the library optional.

Fixed potential sensitive data exposure vulnerability.

### CODE REVIEW

**Comment by yidongnan** [comment]
@ST-DDT If the user is using `HealthCheckingLoadBalancer`, we directly delete the grpc health service, will it affect the grpc call?

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceAutoConfiguration.java [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+import io.grpc.protobuf.services.ProtoReflectionService;
+import net.devh.boot.grpc.server.service.GrpcService;
+
+/**
+ * Auto configuration that sets up the proto reflection service.
+ *
+ * @author Daniel Theuke (daniel.theuke@heuboe.de)
+ */
+@Configuration
+@ConditionalOnClass(ProtoReflectionService.class)
```
Comment (asarkar) [inline grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceAutoConfiguration.java:36]: Where is this class going to come from if not on classpath? I think the check should be a string, not class literal.

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java [hunk 2]
```diff
@@ -110,17 +99,6 @@ protected void configure(final T builder) {
     protected void configureServices(final T builder) {
         final Set<String> serviceNames = new LinkedHashSet<>();
 
-        // support health check
-        if (this.properties.isHealthServiceEnabled()) {
-            builder.addService(this.healthStatusManager.getHealthService());
-            serviceNames.add(HealthGrpc.getServiceDescriptor().getName());
```
Comment (asarkar) [inline grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java:116]: Now that the library no longer adds the health service, how do you recommend users cope with this change? Should they use a `GrpcServerConfigurer` to add it themselves?

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java [hunk 3]
```diff
@@ -180,14 +180,6 @@
...
     private DataSize maxInboundMetadataSize = null;
 
-    /**
-     * Whether gRPC health service is enabled or not. Defaults to {@code true}.
-     *
-     * @param healthServiceEnabled Whether gRPC health service is enabled.
-     * @return True, if the health service is enabled. False otherwise.
-     */
-    private boolean healthServiceEnabled = true;
-
```
Comment (asarkar) [inline grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java:190]: Instead of removing completely, can health not be enabled just like reflection?

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceAutoConfiguration.java (hunk 1 above)
Comment (ST-DDT) [reply grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcReflectionServiceAutoConfiguration.java:36]: The annotation is analyzed by ASM before the class is loaded.
I tested it locally at it works as expected.

If its on a method level, then one has to use strings because the class is already loaded (or failed to be loaded) then.

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java (hunk 2 above)
Comment (ST-DDT) [reply grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/serverfactory/AbstractGrpcServerFactory.java:116]: I can add it back, but I wont populate the service with any defaults anymore, because blindly setting it to SERVING doesnt help with anything.

Just like any other service, you can add it as a simple bean:

````java
@Bean
BindableService healthService(HealthManager healthManager) {
    return healthManager.bindService();
}
````

I strongly recommend NOT adding it via ServerConfigurer as that bypasses all interceptors including security.
Which reminds me, I should add a hint/warning to them.

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java (hunk 3 above)
Comment (ST-DDT) [reply grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/config/GrpcServerProperties.java:190]: Sure, I will add it back.

**Comment by ST-DDT** [comment]
> @ST-DDT If the user is using `HealthCheckingLoadBalancer`, we directly delete the grpc health service, will it affect the grpc call?

I haven't looked into the implementation yet. I will check it.

**Review by yidongnan — APPROVED** [review]

File: grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceAutoConfiguration.java [hunk 4]
```diff
@@ -0,0 +1,60 @@
...
+import io.grpc.services.HealthStatusManager;
+import net.devh.boot.grpc.server.service.GrpcService;
+
+/**
+ * Auto configuration that sets up the grpc health service.
+ *
+ * @author Daniel Theuke (daniel.theuke@heuboe.de)
+ */
+@Configuration
+@ConditionalOnClass(ProtoReflectionService.class)
```
Comment (asarkar) [inline grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceAutoConfiguration.java:38]: @ST-DDT This condition seems wrong. AFAIK, health service has nothing to do with reflection; checking for `HealthStatusManager.class` makes more sense.

Comment (ST-DDT) [reply grpc-server-spring-boot-autoconfigure/src/main/java/net/devh/boot/grpc/server/autoconfigure/GrpcHealthServiceAutoConfiguration.java:38]: Both classes are inside the same jar, so it shouldn't matter.
I will change it for clarity and in case of future refactors/splits.
